variables:
  IMAGE_NAME: py-csco-asa-5500-bckup

stages:
  - build
  - run

docker_build:
  stage: build
  image: docker:20.10.9-dind

  services:
    - docker:20.10.9-dind

  script:
    - docker build -t $IMAGE_NAME .


docker_run:
  stage: run
  image: docker:stable
  script:
    - docker run -d -v /var/run/docker.sock:/var/run/docker.sock -e FIREWALL_USERNAME=$FIREWALL_USERNAME -e FIREWALL_PASSWORD=$FIREWALL_PASSWORD -e BACKUP_SERVER_USERNAME=$BACKUP_SERVER_USERNAME -e BACKUP_SERVER_PASSWORD=$BACKUP_SERVER_PASSWORD -e SMTP_USERNAME=$SMTP_USERNAME -e SMTP_PASSWORD=$SMTP_PASSWORD -e SNMP_USER=$SNMP_USER -e SNMP_AUTH_KEY=$SNMP_AUTH_KEY -e SNMP_PRIV_KEY=$SNMP_PRIV_KEY $IMAGE_NAME
